name: Deploy to Firebase and run cypress tests

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'

      - name: Install required dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Firebase deployment
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  cypress-tests:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'

      - name: Install required dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v5.6.1
        with:
          record: true
          start: npm start
          wait-on: 'http://localhost:4200'
          browser: chrome
          headless: true